load("//nix:flake.bzl", "flake")

flake.cxx_library(
    name = "raylib",
    path = "nixpkgs",
    package = "raylib",
    libs = ["raylib"],
    frameworks = ["OpenGL", "Cocoa", "IOKit", "CoreVideo", "CoreAudio", "AudioToolbox"],
    visibility = ["PUBLIC"],
)
