load("//:defs.bzl", "app")

app(deps = ["//libs/core:core"])

cxx_test(
    name = "server_test",
    srcs = ["server_test.cpp"],
    deps = [
        "//libs/core:core",
        "//nix:gtest",
    ],
)
